### ISSUE TITLE
Functional dependencies list and database design

### ISSUE THREAD

**Issue by ksmolko** [knsjerome/cmpt-354-project#13]
"List of functional dependencies that are applicable to the table (including the ones involving the primary key). For each functional dependency, briefly describe its meaning in English."

**Comment by drowsell** [comment]
Can this issue be closed? Seeing how it looks like this bullet point was removed. See link:
https://canvas.sfu.ca/courses/59580/assignments/618692

**Comment by knsjerome** [comment]
> 
> 
> Can this issue be closed? Seeing how it looks like this bullet point was removed. See link:
> https://canvas.sfu.ca/courses/59580/assignments/618692

The milestone for the issue is "complete project", so this can remain open.
