### ISSUE TITLE
Write functions to parse JSON & Modify SQL tables

### ISSUE THREAD

**Issue by ksmolko** [knsjerome/cmpt-354-project#17]
Refer to the Refer to DB schema in google docs as reference for tables and attribute names that will be created. Also refer to the DB initialization scrip that should be (hopefully) finished by today.

**Comment by knsjerome** [comment]
Some thoughts on this.

Generally, you will be reading the request body of an HTTP request and attempt to decode it into a Go `struct` which has appropriately-tagged `json:...` fields.
