### ISSUE TITLE
Investment Dividend Payout Tracker

### ISSUE THREAD

**Issue by knsjerome** [knsjerome/cmpt-354-project#2]
# Description:
* Tracks Ex-dividend, payout dates, purchase dates and stock’s values
* Keeps track of history of changes from stock as well as other financial information

# Other comments:
* Might be too small of a project idea
* Most data can be taken from Google Finance. I believe they have an API

# Questions:
* Is the Google Finance API rate-limited/paid?
    * "To reiterate, the Google Finance API is no longer supported by Google so it’s undocumented and unreliable. Therefore, this API is best for private toy applications." - https://rapidapi.com/blog/google-finance-api-alternatives/
* What data is available to us through the API(s)?

**Comment by drowsell** [comment]
Good list of APIs:
https://www.reddit.com/r/algotrading/comments/ejg1lr/comprehensive_list_of_api_data_sources/
