### ISSUE TITLE
SFU Optimal Course Picker

### ISSUE THREAD

**Issue by knsjerome** [knsjerome/cmpt-354-project#3]
# Description:
* Contains degree requirements and guesses the best classes to take that fill these requirements and predicts future classes that may be offered.
* Takes into account pre-reqs, grades, courses offered only in specific terms, course time conflicts]

# Other comments:
* SFU calendar has this data available
* Could be difficult to predict future classes due to randomness
* Maybe have a blank elective feature to combat randomness

# Questions:
* How do we get the data reliably?
* How can we ensure that our recommendations are good/valid?

**Comment by drowsell** [comment]
API Link: http://www.sfu.ca/data-hub/api.html
