### ISSUE TITLE
Implement character retrieval (for formal specifications)

### ISSUE THREAD

**Issue by knsjerome** [knsjerome/cmpt-354-project#34]
We need a simple feature to demo for Friday's due formal specifications due date. A (potentially) simple feature is to implement basic character retrieval from preset data.

This involves:

- [x]  Creating a character model that can be used in our database
- [x]  Implementing backend code to fetch a character from our database
- [x]  Create an API endpoint which can be used to fetch characters using an unauthenticated HTTP client
- [ ]  Displaying created character data with a GUI

**Comment by ksmolko** [comment]
Closing as we've got what we need for the formal spec.
