### ISSUE TITLE
Create basic ER diagram for DnD idea

### ISSUE THREAD

**Issue by knsjerome** [knsjerome/cmpt-354-project#4]
We need to describe the entities that exist in our DnD scope and their relationships.

Possible entities:

- Character
- Item
- Spell
- Non-player characters
- Dice

Possible relationships:

- Character <- In party with -> Character
- Character <- Has equipped -> Item
- Character <- Casts -> Spell
- Character <- Rolls -> Dice

**Comment by drowsell** [comment]
ER diagram: https://drive.google.com/file/d/1V1-u3vLMUETvvxpiEBic78i0jrQ8yhMV/view

Modified ER: https://drive.google.com/file/d/1G6UBFOPMND0ccQ6Cgt773CBzHidkpKch/view?usp=sharing

**Comment by drowsell** [comment]
Assignment Requirements: An E/R diagram for the database the application will use. For each entity set, identify candidate keys, and the primary key. For each relationship, identify the cardinality constraint and other constraints, such as participation constraints.

We need to add constraints to the ER diagram.
