### ISSUE TITLE
Create implementation demo video

### ISSUE THREAD

**Issue by ksmolko** [knsjerome/cmpt-354-project#43]
Create a final demo video for the project.

**Comment by knsjerome** [comment]
FYI there are actually _two_ videos: one for specific queries and one showcase video.

**Comment by knsjerome** [comment]
Going to split this into two tickets.

**Comment by drowsell** [comment]
I created this document so we can have a tiny outline for the videos: https://docs.google.com/document/d/1NXLa30OL0byAqdpSin-SXhh5CJz4keEc7mvcpoRgY3k/edit#

I'm trying to put the things we need to show for the requirements. Anyone is free to add or take away anything I wrote.
