### ISSUE TITLE
Reference to Stat Modifier Formulas

### ISSUE THREAD

**Issue by drowsell** [knsjerome/cmpt-354-project#52]
I need the stat modifier formulas for the Character UI Page. If we have them made, or if they are straight from a DND handbook, could someone post a link here.

**Comment by ksmolko** [comment]
https://roll20.net/compendium/dnd5e/Ability%20Scores#content

From what I see: subtract 10 from the ability score and then divide by 2, and that's the ability modifier.

**Comment by drowsell** [comment]
- Strength, Constitution, Wisdom, Dexterity, Charisma, and Intellect:  (x-10)/2
- Proficiency: (Math.ceil((level) / 4) + 1)
- Level is based on XP points that I have to calculate. https://roll20.net/compendium/dnd5e/Character%20Advancement#content
- I don't know if we can derive hit points from hit points max. We may need to track this as I don't know damage taken. 
- Does our Ability_Points refer to Ability Check (I'm pretty sure it does)
- Initiative may not make sense for our DB: https://www.d20srd.org/srd/combat/initiative.htm

**Comment by knsjerome** [comment]
@drowsell Is this closable?
