### ISSUE TITLE
Add Skills to DB schema

### ISSUE THREAD

**Issue by ksmolko** [knsjerome/cmpt-354-project#54]

**Comment by knsjerome** [comment]
This issue needs additional description.

**Comment by ksmolko** [comment]
@knsjerome Yeah I opened this a while ago thinking we might need to implement something that tracks skills, similar to the character sheet here: [https://www.dndtomb.com/wp-content/uploads/2020/12/Screen-Shot-2020-12-30-at-9.23.14-PM.png](url)

After our previous meeting though, it seems we might not need to do this.

**Comment by knsjerome** [comment]
Closing for now. Reopen if still valid.
