### ISSUE TITLE
Full name should be able to contain spaces

### ISSUE THREAD

**Issue by ksmolko** [knsjerome/cmpt-354-project#59]
Entering my full name doesn't work when registering (see image below):

![image](https://user-images.githubusercontent.com/16463725/113383594-2221ee00-9339-11eb-9ffa-b5a3a6b1761a.png)

**Comment by knsjerome** [comment]
Time to change your name, I guess.. =)

**Comment by knsjerome** [comment]
This appears to be an issue with overly-restrictive validation being placed on that field. I'll look into it.
