### ISSUE TITLE
Create Character: Attribute sliders should only accept values between 1 and 30

### ISSUE THREAD

**Issue by ksmolko** [knsjerome/cmpt-354-project#61]
DB will reject values if they exceed 30 (or are 0). Values should be between 1 and 30 (inclusive).

Example: Creating a character with below value will be rejected.

![image](https://user-images.githubusercontent.com/16463725/113384103-2ef31180-933a-11eb-89e1-ac815256648e.png)

**Comment by knsjerome** [comment]
@ksmolko I suspect that @drowsell did not intend this to be a final version of the attribute sliders. This particular UI element was created earlier on before character APIs even existed. I would guess this issue will be rectified in the newer character creation pages.

**Comment by ksmolko** [comment]
Yeah I figured that was the case. I think it might be helpful to leave up anyway just to ensure we don't forget before submitting.

**Comment by drowsell** [comment]
Yes, Kevin is correct. I will make sure all the character data matches the database checks so there will be no conflicts :)
