### ISSUE TITLE
Implement all required query types

### ISSUE THREAD

**Issue by spacebugs** [knsjerome/cmpt-354-project#69]
Queries: Demo a meaningful feature within the context of your application that uses each
of the following types of queries.
o (10 points) **Join query** -- Campaign participants
o (10 points) **Division query** -- DONE (perfect attendance)
o (10 points) **Aggregation query** (functions such as min, max, average or count) -- DONE - Character item weight & value
o (20 points) **Aggregation with group-by** (aggregated value for each group) -- DONE - Character spell count per school
o (10 points) **Delete operation with Cascade** -- DONE - Accounts can be deleted. Characters can be deleted.
o (10 points) **Update operation** -- DONE - User passwords can be changed.

Usability features
o (20 points) **Use of a Responsive Web Design for your front-end implementation.** -- DONE - This is ubiquitous. 
o (20 points) **Use of SQL Assertions and/or triggers functionalities in your project.** -- DONE - Triggers are used to track # of registered players, created campaigns, etc.

**Comment by spacebugs** [comment]
Some ideas..

**Join query**
- Name of all DMs of a Campaign
- All players you have played with
- Characters who are also in same campaign

**Division Query**
- Players who were in every campaigns
- Player who was DM for every game they were in
- Players who were in every game another Player was in

**Aggregation Query**
- Total weight of Characters items
- Players Highest Level Character
- Basically any count

**Aggregation with Group by**
- Players per campaign
- Characters per class
- Characters per Player

**Delete with Cascade:**
- Included with CRUD operations

**Update**
- Included with CRUD operations

**SQL Assertion**
- New Spell level must not be higher than player level
- Limit number of players in a campaign

**Comment by knsjerome** [comment]
FYI PostgreSQL doesn't have assertions.
