### ISSUE TITLE
Should Ability Points be Derived

### ISSUE THREAD

**Issue by drowsell** [knsjerome/cmpt-354-project#73]
We have the stat "ability points" which is the total stat points used by a character. There are two ways to do this: 

- Ability Points could be computed, as the sum of all stat points a character has
- it could be used as a check that the character's stat sum is not greater than the total ability points. 

The second option seem more correct, but may add complexity. Which way should it be implemented?

**Comment by drowsell** [comment]
The maximum amount of Ability Points is 180. There are 30 max points for each ability and 6 different categories). I believe the purpose of these points is to only allow the player to spend so many points (second bullet point in original comment). If we were to implement this property we would need to check that the sum of all abilities is <= to ability points.

**Comment by knsjerome** [comment]
Closing - won't address this due to time constraints.
