### ISSUE TITLE
Not Enough Information to Derive Armor Class

### ISSUE THREAD

**Issue by drowsell** [knsjerome/cmpt-354-project#80]
Armor class is meant to be a derived attribute. I don't believe we have the needed information to derive it based on the DnD rules. 

See the table at the bottom of this link: https://roll20.net/compendium/dnd5e/Armor#content

We would need more specific typing on our items. It may be ideal to scrap AC, unless we wanted to add more complexity to our Items.

**Comment by knsjerome** [comment]
We should just cut armor class if we have no way to obtain this info.
